In [1]:
from bglogUKC import BGLog

In [2]:
bglog = BGLog(debug=True, save_padded_num_sequences=True, load_from_pkl=False)

In [3]:
bglog.tk_path

'C:\\Users\\Bhujay_ROG\\MyDev\\OCLog\\oclog\\BGL\\data\\bgltkukc.pkl'

In [4]:
train_test = bglog.get_tensor_train_val_test(ablation=1000)

log file path found:  True
total number of lines in the log file: 4747963
RAM usage:  39064728
ending logs in memory: 0.8373110294342041
alerts 4747963
unique_alerts: {'SEVERE', '0x00544eb8,', 'Kill', 'ERROR', 'WARNING', 'INFO', 'FATAL', 'FAILURE', 'single', 'microseconds'}
length of list of sequence 148373
elapsed time: 2.265106439590454
self.labelled_txt_sequence: (['- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.823719 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 200

In [6]:
bglog.test_df.label.value_counts()

4    275
0    100
1    100
2    100
3      2
Name: label, dtype: int64

In [29]:
import numpy as np
unique_label_train = np.unique(bglog.train_df.label)
max_label_num_train = max(unique_label_train)
new_label = str(int(max_label_num_train)+1)
print(max_label_num_train)
bglog.test_df.loc[bglog.test_df.label > max_label_num_train, 'label' ]=new_label
# np.where(bglog.test_df.label>max_label_num_train, new_label)
# bglog.test_df[bglog.test_df.label>max_label_num_train].label = str(int(max_label_num_train)+1)
# bglog.test_df.label.value_counts()

3


In [30]:
bglog.test_df.label.value_counts()

4    275
0    100
1    100
2    100
3      2
Name: label, dtype: int64

In [27]:
ndf

'4'

In [5]:
bglog_fm_mem = BGLog(debug=True, load_from_pkl=True)

In [6]:
bglog_fm_mem.get_tensor_train_test(ablation=10)
tk = bglog_fm_mem.tk
print('length of tokenizer from mem', len(tk.word_index))

padded_num_seq_df loaded from data\bgl_padded_num_seq_df.pkl
trained tokenizer, tk, loaded from data\bgltk.pkl
ablation set to : 10
train_0:, 8
test_0:, 2
ablation set to : 10
train_1:, 8
test_1:, 2
ablation set to : 10
train_2:, 8
test_2:, 2
ablation set to : 10
train_3:, 8
test_3:, 2
ablation set to : 10
train_4:, 8
test_4:, 2
ablation set to : 10
train_5:, 8
test_5:, 2
ablation set to : 10
train_6:, 8
test_6:, 2
0    8
1    8
2    8
3    8
4    8
5    8
6    8
Name: label, dtype: int64
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[]
<BatchDataset shapes: ((32, 32, 64), (32, 7)), types: (tf.int32, tf.float32)>
<BatchDataset shapes: ((32, 32, 64), (32, 7)), types: (tf.int32, tf.float32)>
64
7
length of tokenizer from mem 50


In [7]:
import pickle
with open('data\\bgltk.pkl', 'rb') as f:
    tk = pickle.load(f)
len(tk.word_index)

50