In [1]:
from bglog import BGLog

In [2]:
bglog = BGLog(debug=True, save_padded_num_sequences=True, load_from_pkl=False)

In [3]:
bglog.tk_path

'data\\bgltk.pkl'

In [4]:
train_test = bglog.get_tensor_train_test(ablation=1000)

log file path found:  True
total number of lines in the log file: 4747963
RAM usage:  38147016
ending logs in memory: 0.8450729846954346
alerts 4747963
unique_alerts: {'FAILURE', 'ERROR', 'WARNING', 'INFO', 'microseconds', 'single', 'FATAL', 'Kill', 'SEVERE', '0x00544eb8,'}
length of list of sequence 148373
elapsed time: 3.097428560256958
self.labelled_txt_sequence: (['- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.823719 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n', '- 1117838570 200

In [5]:
bglog_fm_mem = BGLog(debug=True, load_from_pkl=True)

In [6]:
bglog_fm_mem.get_tensor_train_test(ablation=10)
tk = bglog_fm_mem.tk
print('length of tokenizer from mem', len(tk.word_index))

padded_num_seq_df loaded from data\bgl_padded_num_seq_df.pkl
trained tokenizer, tk, loaded from data\bgltk.pkl
ablation set to : 10
train_0:, 8
test_0:, 2
ablation set to : 10
train_1:, 8
test_1:, 2
ablation set to : 10
train_2:, 8
test_2:, 2
ablation set to : 10
train_3:, 8
test_3:, 2
ablation set to : 10
train_4:, 8
test_4:, 2
ablation set to : 10
train_5:, 8
test_5:, 2
ablation set to : 10
train_6:, 8
test_6:, 2
0    8
1    8
2    8
3    8
4    8
5    8
6    8
Name: label, dtype: int64
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[]
<BatchDataset shapes: ((32, 32, 64), (32, 7)), types: (tf.int32, tf.float32)>
<BatchDataset shapes: ((32, 32, 64), (32, 7)), types: (tf.int32, tf.float32)>
64
7
length of tokenizer from mem 50


In [7]:
import pickle
with open('data\\bgltk.pkl', 'rb') as f:
    tk = pickle.load(f)
len(tk.word_index)

50