In [1]:
from bglogUKC import BGLog

In [2]:
bglog = BGLog(debug=True, save_padded_num_sequences=True, load_from_pkl=False)

In [3]:
bglog.tk_path

'C:\\Users\\Bhujay_ROG\\MyDev\\OCLog\\oclog\\BGL\\data\\bgltkukc.pkl'

In [4]:
train_test = bglog.get_tensor_train_val_test(ablation=1000, designated_ukc_cls=4)

ablation set to : 1000
log file path found:  True
total number of lines in the log file: 4747963
RAM usage:  39064728
ending logs in memory: 0.8427133560180664
alerts 4747963
unique_alerts: {'ERROR', 'INFO', 'FATAL', 'SEVERE', 'Kill', 'microseconds', 'WARNING', 'FAILURE', 'single', '0x00544eb8,'}
length of list of sequence 148373
elapsed time: 2.2989091873168945
len of whole_text_for_training 4747936
character vocabulary 50
148373
                                                 seq label
0  [[18, 2, 4, 3, 2, 9, 5, 3, 13, 6, 5, 3, 12, 7,...  INFO
1  [[18, 2, 4, 3, 2, 9, 5, 3, 13, 6, 5, 3, 12, 7,...  INFO
2  [[18, 2, 4, 3, 2, 9, 5, 3, 13, 6, 5, 3, 12, 7,...  INFO
3  [[18, 2, 4, 3, 2, 9, 5, 3, 13, 6, 5, 3, 12, 7,...  INFO
4  [[18, 2, 4, 3, 2, 9, 5, 3, 13, 6, 5, 3, 12, 7,...  INFO
0    114115
1     28439
2      4049
3       902
4       628
5       165
6        75
Name: label, dtype: int64
completed padding sequences in 164.74631452560425 sec
trying to save pickle in : C:\Users\Bhujay_ROG\

In [13]:
bglog_fm_mem = BGLog(debug=True, load_from_pkl=True)

In [14]:
bglog_fm_mem.get_tensor_train_val_test(ablation=2000, designated_ukc_cls=5)
tk = bglog_fm_mem.tk
print('length of tokenizer from mem', len(tk.word_index))

ablation set to : 2000
padded_num_seq_df loaded from C:\Users\Bhujay_ROG\MyDev\OCLog\oclog\BGL\data\bgl_ukc.pkl
trained tokenizer, tk, loaded from C:\Users\Bhujay_ROG\MyDev\OCLog\oclog\BGL\data\bgltkukc.pkl
train_0:, 1600
val_0:, 200
test_0:, 200
train_1:, 1600
val_1:, 200
test_1:, 200
train_2:, 1600
val_2:, 200
test_2:, 200
902 data in class 3 not enough to split into train:1600 and validation:200, adding the entire data as ukc
628 data in class 4 not enough to split into train:1600 and validation:200, adding the entire data as ukc
class 5 is add as ukc
ukc_5:, 165
75 data in class 6 not enough to split into train:1600 and validation:200, adding the entire data as ukc
train: 0    1600
1    1600
2    1600
Name: label, dtype: int64
val: 0    200
1    200
2    200
Name: label, dtype: int64
test: 0    200
1    200
2    200
5    165
Name: label, dtype: int64
[[1. 0. 0.]
 [1. 0. 0.]]
some example of labels:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]]
<BatchDataset el

In [9]:
import pickle
with open('data\\bgltk.pkl', 'rb') as f:
    tk = pickle.load(f)
len(tk.word_index)

50

In [10]:
bglog_fm_mem.get_tensor_train_val_test(ablation=100, designated_ukc_cls=4)

<BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 4), dtype=tf.float32, name=None))>
<BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 4), dtype=tf.float32, name=None))>
<BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 6), dtype=tf.float32, name=None))>
64
4


(<BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 4), dtype=tf.float32, name=None))>,
 <BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 4), dtype=tf.float32, name=None))>,
 <BatchDataset element_spec=(TensorSpec(shape=(32, 32, 64), dtype=tf.int32, name=None), TensorSpec(shape=(32, 6), dtype=tf.float32, name=None))>)

In [11]:
bglog_fm_mem.test_df.label.value_counts()

0    100
1    100
2    100
4    100
3      2
Name: label, dtype: int64