In [1]:
from bglog import BGLog

In [2]:
bglog = BGLog(debug=True, save_padded_num_sequences=False, load_from_pkl=True)

In [3]:
train_test = bglog.get_tensor_train_test(ablation=1000)

padded_num_seq_df loaded from data\bgl_padded_num_seq_df.pkl
ablation set to : 1000
train_0:, 800
test_0:, 200
ablation set to : 1000
train_1:, 800
test_1:, 200
ablation set to : 1000
train_2:, 800
test_2:, 200
ablation set to : 1000
train_3:, 800
test_3:, 102
ablation set to : 1000
4 class does not have 800 records, it has only 628 records
test_4:, 0
ablation set to : 1000
5 class does not have 800 records, it has only 165 records
5 class does not have 200 records, it has only 165 records
ablation set to : 1000
6 class does not have 800 records, it has only 75 records
6 class does not have 200 records, it has only 75 records
0    800
1    800
2    800
3    800
Name: label, dtype: int64
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
<BatchDataset shapes: ((32, 32, 64), (32, 4)), types: (tf.int32, tf.float32)>
<BatchDataset shapes: ((32, 32, 64), (32, 4)), types: (tf.int32, tf.float32)>
64
4
