In [2]:
import tensorflow as tf
import numpy as np

In [3]:
txt = ['First']

In [4]:
from char_hdfs import HDFSLog

In [5]:
hdfs = HDFSLog()

In [6]:
logs = hdfs.get_log_lines()

total number of lines in the log file: 11175629


In [8]:
tk = tf.keras.preprocessing.text.Tokenizer(char_level=True)

In [9]:
tk.fit_on_texts(logs)

In [17]:
dir(tk)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_keras_api_names',
 '_keras_api_names_v1',
 'char_level',
 'document_count',
 'filters',
 'fit_on_sequences',
 'fit_on_texts',
 'get_config',
 'index_docs',
 'index_word',
 'lower',
 'num_words',
 'oov_token',
 'sequences_to_matrix',
 'sequences_to_texts',
 'sequences_to_texts_generator',
 'split',
 'texts_to_matrix',
 'texts_to_sequences',
 'texts_to_sequences_generator',
 'to_json',
 'word_counts',
 'word_docs',
 'word_index']

In [18]:
tk.document_count

11175629

In [13]:
len(tk.word_index)

50

In [20]:
s = tk.texts_to_sequences(['First'])
print(s)

[[21, 19, 23, 7, 12]]


In [22]:
tk.sequences_to_texts(s)

['f i r s t']

In [71]:
ids = tk.texts_to_sequences(logs) 

In [72]:
len(ids)

11175629

In [73]:
print(logs[0])

081109 203518 143 info dfs.datanode$dataxceiver: receiving block blk_-1608999687919862906 src: /10.250.19.102:54106 dest: /10.250.19.102:50010


In [74]:
print(ids[0])

[3, 11, 2, 2, 3, 20, 1, 6, 3, 15, 9, 2, 11, 1, 2, 14, 15, 1, 19, 16, 21, 8, 1, 5, 21, 7, 13, 5, 10, 12, 10, 16, 8, 5, 4, 35, 5, 10, 12, 10, 40, 25, 4, 19, 32, 4, 23, 27, 1, 23, 4, 25, 4, 19, 32, 19, 16, 36, 1, 26, 22, 8, 25, 24, 1, 26, 22, 24, 31, 34, 2, 17, 3, 11, 20, 20, 20, 17, 11, 18, 20, 2, 20, 11, 17, 6, 20, 3, 17, 1, 7, 23, 25, 27, 1, 29, 2, 3, 13, 6, 9, 3, 13, 2, 20, 13, 2, 3, 6, 27, 9, 14, 2, 3, 17, 1, 5, 4, 7, 12, 27, 1, 29, 2, 3, 13, 6, 9, 3, 13, 2, 20, 13, 2, 3, 6, 27, 9, 3, 3, 2, 3]


In [75]:
print(tk.sequences_to_texts([ids[0]]))

['0 8 1 1 0 9   2 0 3 5 1 8   1 4 3   i n f o   d f s . d a t a n o d e $ d a t a x c e i v e r :   r e c e i v i n g   b l o c k   b l k _ - 1 6 0 8 9 9 9 6 8 7 9 1 9 8 6 2 9 0 6   s r c :   / 1 0 . 2 5 0 . 1 9 . 1 0 2 : 5 4 1 0 6   d e s t :   / 1 0 . 2 5 0 . 1 9 . 1 0 2 : 5 0 0 1 0']


In [7]:
c1 = [0, 0, 1]
c2 = [0, 1, 0]
c3 = [1, 0, 0]
l1 = [c1, c2]
l2 = [c2, c3]
l3 = [c1, c3]
s1 = [l1, l2]
s2 = [l2, l3]
s3 = [l1, l3]
x = np.array([s1, s2, s3])
print(x.shape)
y = [1, 0, 0]
y = np.array(y)
print(y.shape)

(3, 2, 2, 3)
(3,)


In [95]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv1D(3, 2, input_shape=[2, 2, 3]),
    tf.keras.layers.Dense(1)
                           
                           ])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_4 (Conv1D)            (None, 2, 1, 3)           21        
_________________________________________________________________
dense_4 (Dense)              (None, 2, 1, 1)           4         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer='adam',
    metrics=['accuracy'])

In [102]:
model.fit(x, y, epochs=2)

Epoch 1/2
1/1 [==============================] - 0s 0s/step - loss: 4.5854 - accuracy: 0.4444
Epoch 2/2
1/1 [==============================] - 0s 1ms/step - loss: 4.4717 - accuracy: 0.4444


In [9]:
tfd = tf.data.Dataset.from_tensor_slices((x, y))
tfd = tfd.batch(3)
tfd

<BatchDataset shapes: ((None, 2, 2, 3), (None,)), types: (tf.int32, tf.int32)>

In [107]:
model.fit(tfd, epochs=2)

Epoch 1/2
1/1 [==============================] - 0s 989us/step - loss: 4.4105 - accuracy: 0.4444
Epoch 2/2
1/1 [==============================] - 0s 998us/step - loss: 4.3698 - accuracy: 0.4444


In [19]:
tfd = tf.data.Dataset.from_tensor_slices((x, y))
tfd

<TensorSliceDataset shapes: ((2, 2, 3), ()), types: (tf.int32, tf.int32)>

In [23]:
dataset = tf.data.Dataset.range(5)
print(dataset)
dataset = dataset.map(lambda x: x**2)

<RangeDataset shapes: (), types: tf.int64>


In [28]:
tfd_flat = tfd.map(lambda x, y: (tf.reshape(x, (2, 6)), y))
tfd_flat

<MapDataset shapes: ((2, 6), ()), types: (tf.int32, tf.int32)>

In [29]:
for x in tfd_flat:
    print(x)

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0]])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 0]])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [30]:
for x in tfd:
    print(x)

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 1],
        [0, 1, 0]],

       [[0, 1, 0],
        [1, 0, 0]]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 1, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [1, 0, 0]]])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 1],
        [1, 0, 0]]])>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
