In [6]:
from hdflogv1 import HDFSLogv1
import tensorflow as tf
import numpy as np
tf.random.set_seed(123)
import pickle

In [2]:
hdfslogs = HDFSLogv1(padded_seq_len=32,
                         padded_char_len=64)

In [3]:
padded_data = hdfslogs.get_padded_train_test_data()

total number of lines in the log file: 11175629
RAM usage:  91719104
ending logs in memory: 5.253721714019775
loaded cleaned logs with blk_id  in memory: 89.4391872882843
RAM usage:  91719104
loaded cleaned logs without blkid in memory: 0.4410388469696045
RAM usage:  91719104
starting training the tokenizer:
ending tokenizer training: 183.61084413528442
RAM usage:  48
vocabulary size: 42
starting text to number conversion
completed:  0
time : 0.0
completed:  1000000
time : 16.5333034992218
completed:  2000000
time : 31.730684280395508
completed:  3000000
time : 48.962820529937744
completed:  4000000
time : 65.35843014717102
completed:  5000000
time : 82.02002739906311
completed:  6000000
time : 98.68645477294922
completed:  7000000
time : 115.7013008594513
completed:  8000000
time : 132.62197065353394
completed:  9000000
time : 149.62989830970764
completed:  10000000
time : 166.54741525650024
completed:  11000000
time : 183.4408519268036
ending text to number conversion: 186.5173549652

In [4]:
x_train, y_train, x_test, y_test = padded_data

In [5]:
x_train[0][0]

array([ 4,  7, 13,  3, 10,  2, 11,  2,  4, 23,  4,  7, 24, 15, 12,  3, 11,
       14,  8, 10, 11, 19,  5,  2,  8,  6, 19,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [6]:
tk = hdfslogs.tk
print(tk.sequences_to_texts(x_train[0]))
print(y_test[0])

['i n f o r e c e i v i n g b l o c k s r c : d e s t : UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'r o o t r a n d 7 _ t e m p o r a r y _ t a s k _ 2 0 0 8 1 1 1 0 1 0 2 4 _ 0 0 1 4 _ m _ 0 0 0 6 2 3 _ 0 p a r t - 0 0 6 2 3 .', 'i n f o r e c e i v i n g b l o c k s r c : d e s t : UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'b l o c k r e c e i v e d e x c e p t i o n j a v a . i o . i o e x c e p t i o n : c o u l d n o t r e a d f r o m s t r e a m', 'UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK

In [7]:
print(tk.sequences_to_texts(x_train[1]))
print(y_test[1])

['i n f o r e c e i v i n g b l o c k s r c : d e s t : UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'i n f o r e c e i v i n g b l o c k s r c : d e s t : UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'i n f o r e c e i v i n g b l o c k s r c : d e s t : UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'r r o o t r a n d _ t e m p o r a r y _ t a s k _ 2 0 0 8 1 1 0 9 2 0 3 0 _ 0 0 0 1 _ m _ 0 0 1 2 0 8 _ 0 p a r t - 0 1 2 0 8 .', 'i n f o p a c k e t r e s p o n d e r 0 f o r b l o c k t e r m i n a t i n g UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK', 'i n f o r e c e i v e d b l o c k o f s i z e 6 7 1 0 8 8 6 4 f r o m U

In [3]:
ablation_data = hdfslogs.get_train_test_data(ablation=1000)

total number of lines in the log file: 11175629
RAM usage:  91719104
ending logs in memory: 5.3517234325408936
loaded cleaned logs with blk_id  in memory: 87.69729948043823
RAM usage:  91719104
loaded cleaned logs without blkid in memory: 0.448652982711792
RAM usage:  91719104
starting training the tokenizer:
ending tokenizer training: 184.1769437789917
RAM usage:  48
vocabulary size: 42
starting text to number conversion
completed:  0
time : 0.0
completed:  1000000
time : 16.56307053565979
completed:  2000000
time : 31.8032648563385
completed:  3000000
time : 48.934873819351196
completed:  4000000
time : 65.34685850143433
completed:  5000000
time : 81.88243174552917
completed:  6000000
time : 98.55234456062317
completed:  7000000
time : 115.54704546928406
completed:  8000000
time : 132.530690908432
completed:  9000000
time : 149.71746969223022
completed:  10000000
time : 166.7537932395935
completed:  11000000
time : 183.7383234500885
ending text to number conversion: 186.8066968917846

In [4]:
x_train, y_train, x_test, y_test = hdfslogs.get_padded_train_test_data()
x_train.shape

length of train  sequence original 4
length of train  sequence original 25
length of train  sequence original 33
length of train  sequence original 21
length of train  sequence original 2
length of train sequence padded 32
length of train sequence padded 32
length of train sequence padded 32
length of train sequence padded 32
length of train sequence padded 32
len of test seq after padding 32
len of test seq after padding 32
len of test seq after padding 32
len of test seq after padding 32
len of test seq after padding 32
padded_train_test_data done: 6.604649066925049
RAM usage padded_train_test_data:  72


(2000, 32, 64)

In [9]:
with open('hdfs_log_obj.pkl', 'wb') as f:
    pickle.dump(hdfslogs, f)

In [10]:
y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [11]:
import tensorflow as tf
B = 32
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_data = train_data.shuffle(buffer_size=y_train.shape[0]).batch(B, drop_remainder=True)
train_data

<BatchDataset shapes: ((32, 32, 64), (32,)), types: (tf.int32, tf.int64)>

In [43]:
inputs = tf.keras.layers.Input(batch_shape=(B, 32, 64), dtype='float64' )
x = tf.keras.layers.Conv1D(filters=64, kernel_size=3, padding='same')(inputs)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(2048)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
model.compile(optimizer='adam', 
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Model: "functional_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(32, 32, 64)]            0         
_________________________________________________________________
conv1d_10 (Conv1D)           (32, 32, 64)              12352     
_________________________________________________________________
flatten_3 (Flatten)          (32, 2048)                0         
_______________________

In [44]:
model.fit(train_data, epochs=10)

Epoch 1/10
62/62 [==============================] - 1s 17ms/step - loss: 0.6956 - accuracy: 0.4970
Epoch 2/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6838 - accuracy: 0.5302
Epoch 3/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6834 - accuracy: 0.5333
Epoch 4/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.4995
Epoch 5/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.4990
Epoch 6/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.5000
Epoch 7/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.5000
Epoch 8/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.4995
Epoch 9/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.5010
Epoch 10/10
62/62 [==============================] - 1s 18ms/step - loss: 0.6931 - accuracy: 0.5015


In [14]:
tk = hdfslogs.tk
vocab_size = len(tk.word_index)
print(f'vocab_size: {vocab_size}')
char_onehot = vocab_size

vocab_size: 42


In [15]:
import numpy as np
embedding_weights = []
embedding_weights.append(np.zeros(vocab_size))
for char, i in tk.word_index.items(): # from 1 to 51
    onehot = np.zeros(vocab_size)
    onehot[i-1] = 1
    embedding_weights.append(onehot)
embedding_weights = np.array(embedding_weights)

In [48]:
print(embedding_weights.shape) # first row all 0 for PAD and last row for UNK
embedding_weights

(43, 42)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [16]:
input_size = [32, 64]
embedding_size = 42

embedding_layer = tf.keras.layers.Embedding(vocab_size+1,
                                            embedding_size,
                                            input_length=input_size,
                                            weights = [embedding_weights])
embedding_layer

In [54]:
inputs = tf.keras.layers.Input(batch_shape=(B, 32, 64), dtype='float64' )
x = tf.keras.layers.Embedding(input_dim=vocab_size+1,
                                output_dim=embedding_size,
                                input_length=64,
                                weights = [embedding_weights],
                                )(inputs)
x = tf.keras.layers.Conv1D(filters=64, kernel_size=3, padding='same')(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(2048)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
model.compile(optimizer='adam', 
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

Model: "functional_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(32, 32, 64)]            0         
_________________________________________________________________
embedding_4 (Embedding)      (32, 32, 64, 42)          1806      
_________________________________________________________________
conv1d_12 (Conv1D)           (32, 32, 64, 64)          8128      
_________________________________________________________________
flatten_5 (Flatten)          (32, 131072)              0         
_________________________________________________________________
dense_16 (Dense)             (32, 2048)                268437504 
_________________________________________________________________
dense_17 (Dense)             (32, 1)                   2049      
Total params: 268,449,487
Trainable params: 268,449,487
Non-trainable params: 0
_______________________________________

In [55]:
model.fit(train_data, epochs=10)

Epoch 1/10
62/62 [==============================] - 54s 878ms/step - loss: 0.6554 - accuracy: 0.5988
Epoch 2/10
62/62 [==============================] - 55s 886ms/step - loss: 0.6523 - accuracy: 0.6094
Epoch 3/10
62/62 [==============================] - 54s 878ms/step - loss: 0.6522 - accuracy: 0.6074
Epoch 4/10
62/62 [==============================] - 55s 883ms/step - loss: 0.6523 - accuracy: 0.6099
Epoch 5/10
62/62 [==============================] - 55s 881ms/step - loss: 0.6520 - accuracy: 0.6094
Epoch 6/10
62/62 [==============================] - 56s 901ms/step - loss: 0.6525 - accuracy: 0.6069
Epoch 7/10
62/62 [==============================] - 55s 882ms/step - loss: 0.6525 - accuracy: 0.6089
Epoch 8/10
62/62 [==============================] - 55s 886ms/step - loss: 0.6523 - accuracy: 0.6074
Epoch 9/10
62/62 [==============================] - 55s 888ms/step - loss: 0.6522 - accuracy: 0.6099
Epoch 10/10
62/62 [==============================] - 55s 888ms/step - loss: 0.6522 - accura

In [17]:
inputs = tf.keras.layers.Input(batch_shape=(B, 32, 64), dtype='float64' )
x = tf.keras.layers.Embedding(input_dim=vocab_size+1,
                                output_dim=embedding_size,
                                input_length=64,
                                weights = [embedding_weights],
                                )(inputs)
x = tf.keras.layers.Conv1D(filters=64, kernel_size=6, padding='same')(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(2048)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
model.compile(optimizer='adam', 
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])


Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(32, 32, 64)]            0         
_________________________________________________________________
embedding_1 (Embedding)      (32, 32, 64, 42)          1806      
_________________________________________________________________
conv1d (Conv1D)              (32, 32, 64, 64)          16192     
_________________________________________________________________
flatten (Flatten)            (32, 131072)              0         
_________________________________________________________________
dense (Dense)                (32, 2048)                268437504 
_________________________________________________________________
dense_1 (Dense)              (32, 1)                   2049      
Total params: 268,457,551
Trainable params: 268,457,551
Non-trainable params: 0
________________________________________

In [18]:
model.fit(train_data, epochs=3)

Epoch 1/3
62/62 [==============================] - 56s 899ms/step - loss: 0.6590 - accuracy: 0.5938
Epoch 2/3
62/62 [==============================] - 57s 915ms/step - loss: 0.6570 - accuracy: 0.5948
Epoch 3/3
62/62 [==============================] - 56s 898ms/step - loss: 0.6562 - accuracy: 0.5973
